language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO="Django>=1.7.0,<1.8.0"
  - DJANGO="Django>=1.8.0,<1.9.0"
  - DJANGO="Django>=1.9.0,<1.10.0"
  - DJANGO="Django>=1.10.0,<1.11.0"
  - DJANGO="Django>=1.11.0,<2.0.0"
  - DJANGO="Django>=2.0.0,<2.1.0"
  - DJANGO="Django>=2.1.0,<2.2.0"

install:
    - pip install -q $DJANGO
    - pip install coveralls

script:
  - coverage run runtests.py
  
after_success:
  - coveralls

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="Django>=1.7.0,<1.8.0"
    - python: "3.6"
      env: DJANGO="Django>=1.7.0,<1.8.0"
    
    - python: "3.6"
      env: DJANGO="Django>=1.8.0,<1.9.0"
    
    - python: "3.3"
      env: DJANGO="Django>=1.9.0,<1.10.0"
    - python: "3.6"
      env: DJANGO="Django>=1.9.0,<1.10.0"
    
    - python: "3.3"
      env: DJANGO="Django>=1.10.0,<1.11.0"
    - python: "3.6"
      env: DJANGO="Django>=1.10.0,<1.11.0"
    
    - python: "3.3"
      env: DJANGO="Django>=1.11.0,<2.0.0"
    
    - python: "2.7"
      env: DJANGO="Django>=2.0.0,<2.1.0"
    - python: "3.3"
      env: DJANGO="Django>=2.0.0,<2.1.0"
    
    - python: "2.7"
      env: DJANGO="Django>=2.1.0,<2.2.0"
    - python: "3.3"
      env: DJANGO="Django>=2.1.0,<2.2.0"
    - python: "3.4"
      env: DJANGO="Django>=2.1.0,<2.2.0"
